### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by eXidusLive** [tungstonminer/istari#38]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

Yes I have experience playing on many modded minecraft servers.  Mostly singleplayer though I have done a lot of online as well. 

*Have you successfully been able to play *this modpack* in single-player?*

Yes, I have.  I was able to load into the world and I assume it's working as I have "Hobbits / Stranger" at the top of my screen.  

*What is your Minecraft username?*

eXidesLive

### Please re-state the server rules in your own words

*** Player vs Player combat is not allowed unless agreed upon by both parties involved.  In other words, don't randomly kill people because you can. 

*** Don't grief other players creatives / buildings as someone I'm sure has worked hard on that and likely wouldn't enjoy logging into what use to be their homes. 

*** Refrain from building anywhere near anyone else as it can ruin the immersion of that persons build with whatever style of build you plan on making, looking out your front window and seeing a floating spaceship from your medieval town just doesn't make sense, lets not forget about that fact that it wouldn't make sense in this world.  (Find remote locations to build your creations unless given permission otherwise)

*** When creating your build you should always have a plan.  Walls around your town?  Houses, cam fires.. etc etc.  Detail is key when it comes to building, try not to make your building look like default Minecraft. ( In this case, id likely be building around Misty Mountains, cave system, housing within the mountain. (As long as it's not taken by anyone else or any NPC buildings as I'm sure it may be depending on the scale or scope of the server itself.  

I know it's not requested but here are some images of my previous server that I build as record of my building style.   This build below was done within 2 days on a survival server non creative.  When I focus on something I tend to go a little overboard. 

https://ibb.co/8XFftSF
https://ibb.co/6BNQcNr
https://ibb.co/pwLdhVq
https://ibb.co/RDx3Gfk

*** Last but not least, don't randomly destroy the world because you need materials.   Sometimes it cant be helped as you may need a very large amount of dirt, In this case id simple only take half layers working my way up or down layers to even them out making it look natural as I took the dirt.  Outside of that, leave things as you found them unless you plan to do something on that land. 

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Good morningeXidusLive.  You've been added to the server.  You may start playing Istari!  If you have any problems, please let me know, otherwise, I will close this tomorrow.

**Comment by eXidusLive** [comment]
Wonderful, thank you.

**Comment by GnarlyOldGuy** [comment]
Access request completed.
