### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by DJGAMINGM6** [tungstonminer/istari#39]
### Please answer the following questions

*What is your experience playing modded Minecraft?* been playing modded for years.

*Have you successfully been able to play *this modpack* in single-player?* havent played the modpack yet.

*What is your Minecraft username?* DJGAMINGM6

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Please go to the following link, https://github.com/tungstonminer/istari/wiki/Server read and restate the rules as requested above.
We also highly recommend you load the mod pack and try it in a single instance to get familiar with the mod pack.
Once you've updated above, I will come back and check.

**Comment by GnarlyOldGuy** [comment]
No response to the request to update.  Closing request.
