### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Ce1ebria** [tungstonminer/istari#40]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I've played various versions of modded minecraft from as far back as 2016 FTB unleashed was my first experience and I've since expanded into other packs over the years, from skyblock to crashlanded, stoneblock to roguelike adventure dungeons. I've played on both forge and fabric clients and had experience running modded servers more recently.

*Have you successfully been able to play *this modpack* in single-player?*
Yes

*What is your Minecraft username?*
Celebria_
### Please re-state the server rules in your own words
No PvP with neutral or allied players
Do not grief others, either by destroying/altering their builds or building anything near them that disrupts their enjoyment 
Do not destroy the landscape and leave eye sores around. We're not Saruman and the Ents don't appreciate that behaviour!
Essentially - Don't be a douche

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Hello, thanks for filling out the requested information.  You have been added to the server whitelist.
I will leave this open for another 24 hours in case you have any problems.

**Comment by Ce1ebria** [comment]
Thank you muchly.

**Comment by GnarlyOldGuy** [comment]
Access granted.  No further help was requested, closing issue.
