### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by NukaC0la** [tungstonminer/istari#43]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
 I have numerous hours put into many, MANY modpacks, so I am fairly familiar with a lot of mods, in many iterations of those mods.
*Have you successfully been able to play *this modpack* in single-player?*
 I have, Yes.
*What is your Minecraft username?*
NukaColaa
### Please re-state the server rules in your own words
In generalizing the rules, be kind, don't be an ass, and don't grief. Things shouldn't be missing, be it items, terrain, or people in any form.
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
I apologize for taking a little longer than promised.  You have been granted access to the server.  I will leave this open for a couple of days in case you have any problems.

**Comment by GnarlyOldGuy** [comment]
No follow-up questions, I'm closing this issue.
