### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by BlocksterA** [tungstonminer/istari#48]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I mostly make custom modpack to mess around with mods and like playing modded Minecraft with other people.
*Have you successfully been able to play *this modpack* in single-player?*
I have not yet downloaded the pack.
*What is your Minecraft username?*
BlocksterA
### Please re-state the server rules in your own words
No pvp with neutral players or factions
Don't destroy other players creations
Don't tear up the terrain for no reason
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Sounds good!  Welcome to the server!  If you run into any problems, feel free to ask for help on the Discord channel.
