### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/istari#49]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I have been playing modded Minecraft for around three years, and I have been playing Minecraft in general for about six.

*Have you successfully been able to play *this modpack* in single-player?*
Yes, I have been able to play successfully.

*What is your Minecraft username?*
TheOne21

### Please re-state the server rules in your own words
1.) No PVP with neutral of allied players.
2.) No griefing/destroying builds that are not yours.
3.) No destroying the landscape (presumably talking about TNT, End Crystals, etc.) unless you can make something better from it.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Sounds good!  Welcome to the server!  If you run into any problems, feel free to ask for help on the Discord channel.
