### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by DragonLord121206** [tungstonminer/istari#50]
### Please answer the following questions

*What is your experience playing modded Minecraft?* I have been play modded Minecraft since 2017 and I have a great general knowledge of mods

*Have you successfully been able to play *this modpack* in single-player?* I have played this pack yet

*What is your Minecraft username?* Dragon121206

### Please re-state the server rules in your own words:
no killing neutral players or players allied with you
do not grief other players builds and ask permission
if you dig or mine a big area please make something in it to make it not look ugly

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Sounds good!  Welcome to the server!  If you run into any problems, feel free to ask for help on the Discord channel.
