### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Fireoverlord13** [tungstonminer/istari#51]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

*Have you successfully been able to play *this modpack* in single-player?*

*What is your Minecraft username?*

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:24565`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by Fireoverlord13** [comment]
I have been playing modded for around 6-8 months I believe by now,
Yes I have
Fireoverlord13
I must not kill any and all allied players (that includes neutral ones)
I must always ask for permission to modify and or building near other people's builds,
I must not destroy the world without an excuse or purpose

**Comment by tungstonminer** [comment]
Sounds good!  Welcome to the server!  If you run into any problems, feel free to ask for help on the Discord channel.
