### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by PdQuinn82** [tungstonminer/istari#54]
### Please answer the following questions

*What is your experience playing modded Minecraft?* I've been playing since beta. 

*Have you successfully been able to play *this modpack* in single-player?* Yes

*What is your Minecraft username?* Krundicus

### Please re-state the server rules in your own words

The rules are fairly simple, No pvp with those who are neutral or members of allied groups, Don't grief others structures or build near them unless you get permission and don't dig up/alter the landscape, without improving it. 

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
