### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by idkanymore103** [tungstonminer/istari#55]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

*Have you successfully been able to play *this modpack* in single-player?*

*What is your Minecraft username?*

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by idkanymore103** [comment]
*What is your experience playing modded Minecraft?*
I prefer it over vanilla, so i know it quite well

*Have you successfully been able to play *this modpack* in single-player?*
Yes

*What is your Minecraft username?*
AlexanderIsUWU

### Please re-state the server rules in your own words
Dont attack players without consent 
Dont grief anything that looks like a players made
Dont build near another player without asking
Add a sign with your name to your build
Dont make the landscape look ugly

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
