### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Unnamedg** [tungstonminer/istari#58]
### Please answer the following questions

*What is your experience playing modded Minecraft?* Pretty good 

*Have you successfully been able to play *this modpack* in single-player?* Yes 

*What is your Minecraft username?* Unam3d_

### Please re-state the server rules in your own words: 
1. Don't PVP with people that are neutral and with people that are allied faction. 
2. Don't mess with people's builds or build near them unless you have permission.
3. Don't mess up the landscape unless your going to make it better looking.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
