### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Dare0900** [tungstonminer/istari#59]
*What is your experience playing modded Minecraft?*
I have considerable experience with newer versions of modded minecraft, but so far I've focused on tech mods a lot. I wanted to get a bit of a break from that here, because I've heard wonderful things about Thaumcraft 4. 

*Have you successfully been able to play *this modpack* in single-player?*
Yes, no problems that I could see

*What is your Minecraft username?*
alcyonestus

### Please re-state the server rules in your own words
Rule 1: PvP is only allowed if the other person agrees to it. No random attacking
Rule 2: Leave the works of others alone. Don't break their stuff, don't add to their build, and don't build directly next to them
Rule 3: Don't just make a giant quarry in the ground. If the scenery is going to be destroyed, it better be for a good reason

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
