### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by isabellemeredith** [tungstonminer/istari#60]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I’ve been playing modded Minecraft for about the past 9 years, and modpacks for about the past 5. 

*Have you successfully been able to play *this modpack* in single-player?*

Yes the pack launched and I successfully made a world, though I’ve only played a couple minutes.

*What is your Minecraft username?*

izzlefrizlle

### Please re-state the server rules in your own words

Don’t initiate pvp without asking, don’t grief other people’s builds, don’t build in sight of other people’s builds without asking (is that 8 chunks? I don’t expect it to come up but some people have much higher render distances than others) make it obvious builds are yours, don’t ruin the landscape without repairing or improving it.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
