### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by ArcwinPFS** [tungstonminer/istari#62]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I've played a few modpacks, just poking around.  CTE Dissonance, Stoneblock, and currently playing in Astral Botanic Mage-tastic Wizardry mod.  Haven't played anything with Thaumcraft yet, so it will be fun to learn.

*Have you successfully been able to play *this modpack* in single-player?*
Just enough to get it going and see I have no problems running it.

*What is your Minecraft username?*
CatlikeCat9766

### Please re-state the server rules in your own words
Be polite and don't ruin the other players' experience.  
Pvp only with opposing faction, not neutrals or allies.  Don't wreck the landscape: like deforestation without replanting trees, leaving holes all over, etc.  But building is okay - just not in sight of others' works (save with permission).

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.

**Comment by ArcwinPFS** [comment]
When I start Minecraft, it says CatlikeCat9766 (microsoft account)

**Comment by GnarlyOldGuy** [comment]
When you are in the game itself, what is your screen name?  That is the UID I need to add you to the server.

**Comment by ArcwinPFS** [comment]
ArcwinPFS

**Comment by ArcwinPFS** [comment]
ArcwinPFS (is my screen name, I mean)  I wasn't able to find a way to see a view with my name over my head or something, but after a while I realized I could just say something in chat.  Felt silly for not thinking of it sooner.

**Comment by GnarlyOldGuy** [comment]
You've been added, you are good to go now.
