### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by IamForeverAlone** [tungstonminer/istari#64]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I play different mod packs from time to time and I basically learned the basics of every popular mod, like thaumcraft etc...

*Have you successfully been able to play *this modpack* in single-player?*
Yes

*What is your Minecraft username?*
Pyrorogue3

### Please re-state the server rules in your own words
.Do not engage in combat unless provoked
.Do not grief nor touch any buildings that appear to have been made by another player
.Do not build near another players vicinity unless you gained permission
.Make it easy for players to identify that you are building something
.Do not destroy the landscapes without making creating something better out of it

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
