### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Shiridari** [tungstonminer/istari#65]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I've played Minecraft for a couple of years now. When it comes to modded Minecraft, I've done a playthrough of Blightfall and some other modpacks. 

*Have you successfully been able to play *this modpack* in single-player?*

I have not be able to play the modpack in single-player.

*What is your Minecraft username?*

Shiridari

### Please re-state the server rules in your own words

The server doesn't allow pvp combat that's uninvited. Don't disturb things made by, or look like they may have been made by another player. Don't build anything in view of another person's land without asking permission first. Don't make it difficult for other people to be able to tell that you made something. Don't tear up the land without actually doing something with it; Its not cool walking around and seeing blown-up holes in the ground everywhere. 

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
