### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Prostoarc** [tungstonminer/istari#70]
> What is your experience playing modded Minecraft?

I started playing minecraft since 2012.

> Have you successfully been able to play the modpack in single-player?

Yep.

> What is your Minecraft username?

Tezacarius

> Please re-state the server rules in your own words

Be polite in communication.
Do not disturb other players (if they didn't allow pvp, building, etc.)
Do not litter the world with horrible object (earth pillars, etc.)

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.
