### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by gjgjn1004** [tungstonminer/istari#81]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I played in some servers
*Have you successfully been able to play *this modpack* in single-player?*
Yes
*What is your Minecraft username?*
gjgjn1004
### Please re-state the server rules in your own words
Don't ruin the landscape if you don't need it, do not be toxic to other players and ruin there building's or build near them without permission.  Make sure to at least build something on your land to let other players know that they should ask your permission before doing anything there. No attacking players if they don't agree and no griefing.
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`istari.tungstonminer.com:25654`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/istari/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by GnarlyOldGuy** [comment]
Sounds good! Welcome to the server! If you run into any problems, feel free to ask for help on the Discord channel.

Please read the following post on Discord so you are fully aware of our expectations:

[Just don't do it and protect yourself](https://discord.com/channels/340980451076210699/880583575152513025/891760103781453914)

[TM's confirmation](https://discord.com/channels/340980451076210699/880583575152513025/891796404270399538)

[Make sure your Discord User Name matches your in-game name](https://discord.com/channels/340980451076210699/880583575152513025/891809099606552586)
